Title: Exceptions¶
URL: https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError

Queues

Event Loop

Report a Bug

Show Source

index

modules |

next |

previous |



Python »





3.13.2 Documentation »

The Python Standard Library »

Networking and Interprocess Communication »

asyncio — Asynchronous I/O »

Exceptions

|

Theme Auto Light Dark |

Source code: Lib/asyncio/exceptions.py

A deprecated alias of TimeoutError , raised when the operation has exceeded the given deadline.

Changed in version 3.11: This class was made an alias of TimeoutError .

The operation has been cancelled.

This exception can be caught to perform custom operations when asyncio Tasks are cancelled.  In almost all situations the exception must be re-raised.

Changed in version 3.8: CancelledError is now a subclass of BaseException rather than Exception .

Invalid internal state of Task or Future .

Can be raised in situations like setting a result value for a Future object that already has a result value set.

The "sendfile" syscall is not available for the given socket or file type.

A subclass of RuntimeError .

The requested read operation did not complete fully.

Raised by the asyncio stream APIs .

This exception is a subclass of EOFError .

The total number ( int ) of expected bytes.

A string of bytes read before the end of stream was reached.

Reached the buffer size limit while looking for a separator.

Raised by the asyncio stream APIs .

The total number of to be consumed bytes.

Queues

Event Loop

Report a Bug

Show Source

index

modules |

next |

previous |



Python »





3.13.2 Documentation »

The Python Standard Library »

Networking and Interprocess Communication »

asyncio — Asynchronous I/O »

Exceptions

|

Theme Auto Light Dark |